'use strict';
/* ────────────────────────────────────────────────────────────────
   Build the static bundle in dist/ — everything a plain web host
   needs, with no Node running behind it.

   Two things cannot survive without the server, and this script
   handles both rather than shipping dead UI:

     /api/library → baked into assets/snapshot.js at build time, so
                    the counts are real YouTube figures, just frozen.
     /api/meta    → the Meta lookup section is cut from the page. It
                    needs a secret token on every query, and a static
                    host has nowhere to keep one.

   Run with the dev server up so the snapshot is fresh:
       npm start          (in one terminal)
       npm run build      (in another)
   ──────────────────────────────────────────────────────────────── */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const API = process.env.BUILD_API || 'http://localhost:8123';

const say = (...a) => console.log(' ', ...a);

/* ── 1. fresh dist ───────────────────────────────────────────── */
fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(path.join(DIST, 'assets'), { recursive: true });

/* ── 2. the view-count snapshot ──────────────────────────────── */
async function snapshot() {
  let payload = null;
  try {
    const res = await fetch(`${API}/api/library`, { signal: AbortSignal.timeout(15_000) });
    payload = await res.json();
  } catch {
    say('! server not reachable at', API);
  }

  if (!payload || !payload.live) {
    say('! no live counts baked — the page will show the bundled estimates.');
    say('  Start the server with a YOUTUBE_API_KEY set, then build again.');
    return { live: false, stats: {} };
  }
  say(`✓ baked ${Object.keys(payload.stats).length} live counts, fetched ${payload.fetchedAt}`);
  return { live: true, fetchedAt: payload.fetchedAt, stats: payload.stats };
}

/* ── 3. the page, minus what cannot work ─────────────────────── */
function page(html) {
  /* Drop the Meta lookup section — it needs a server-held token. */
  const start = html.indexOf('  <!-- ─────────────────────────── LIVE / META');
  const end = html.indexOf('  <!-- ─────────────────────────── PRINCIPLES');
  if (start === -1 || end === -1) {
    throw new Error('Could not find the Meta section markers in index.html — ' +
      'the comment banners moved. Fix the markers in scripts/build.js.');
  }
  html = html.slice(0, start) + html.slice(end);

  /* Flip the front end into static mode and load the snapshot ahead
     of live.js, which reads window.AA_SNAPSHOT on boot. */
  html = html.replace(
    '<script src="assets/live.js"></script>',
    '<script>window.AA_STATIC=true</script>\n' +
    '  <script src="assets/snapshot.js"></script>\n' +
    '  <script src="assets/live.js"></script>'
  );
  return html;
}

/* ── 4. go ───────────────────────────────────────────────────── */
(async () => {
  const snap = await snapshot();
  fs.writeFileSync(
    path.join(DIST, 'assets', 'snapshot.js'),
    `/* Generated by npm run build — do not edit. */\n` +
    `window.AA_SNAPSHOT=${JSON.stringify(snap)};\n`
  );

  const html = page(fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8'));
  fs.writeFileSync(path.join(DIST, 'index.html'), html);

  const assets = fs.readdirSync(path.join(ROOT, 'assets'));
  for (const f of assets) {
    fs.copyFileSync(path.join(ROOT, 'assets', f), path.join(DIST, 'assets', f));
  }
  say(`✓ copied ${assets.length} assets`);

  /* Apache hosts (cPanel) serve .js as text/plain in some configs, which
     kills ES modules. Force the type and turn on compression. */
  fs.writeFileSync(path.join(DIST, '.htaccess'), [
    'AddType text/javascript .js',
    'AddType text/css .css',
    '',
    '<IfModule mod_deflate.c>',
    '  AddOutputFilterByType DEFLATE text/html text/css text/javascript application/json',
    '</IfModule>',
    '',
    '# Long cache for fingerprint-free assets is wrong here — the file names',
    '# never change, so a stale copy would outlive a deploy. One hour.',
    '<IfModule mod_expires.c>',
    '  ExpiresActive On',
    '  ExpiresByType text/css "access plus 1 hour"',
    '  ExpiresByType text/javascript "access plus 1 hour"',
    '  ExpiresByType text/html "access plus 5 minutes"',
    '</IfModule>',
    ''
  ].join('\n'));

  say('✓ wrote .htaccess');
  console.log(`\nBuilt → ${DIST}\nUpload the CONTENTS of dist/ into public_html/ (not the folder itself).\n`);
})();
